version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
<<<<<<< HEAD
      args:
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"
    env_file:
        - .env

    volumes:
      - ..:/workspace:cached  
=======

    volumes:
      - ../..:/workspaces:cached
>>>>>>> 82094ba (first test with devcontainer)

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

<<<<<<< HEAD
    # Uncomment the next line to use a non-root user for all processes.
    user: dev

=======
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
>>>>>>> 82094ba (first test with devcontainer)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
<<<<<<< HEAD
    env_file:
        - .env
=======
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
>>>>>>> 82094ba (first test with devcontainer)

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
